### ISSUE TITLE
Arrow points in the wrong direction

### ISSUE THREAD

**Issue by jobremer** [OpenTrafficCam/OTGroundTruther#65]
- In many cases the arrow indicating the direction of the object from an imported otevents-file points in the wrong direction. Additionally, the shown Enter Time is in fact the "leave time" and the Time Span is negative. 
- The ottrk-data itself is correct.

![grafik](https://github.com/OpenTrafficCam/OTGroundTruther/assets/118731573/6c7f2a37-d759-46f5-8735-9328b274e9ba)

![grafik](https://github.com/OpenTrafficCam/OTGroundTruther/assets/118731573/227a81b0-e163-46fa-88a1-583e74ad378e)

**Comment by arminkollascheck** [comment]
Thanks for your bug report and sry for the late answer. Can you share the files that you used in this example? I want to reproduce it, since with the otevents/video files I tested I dont face this problems. In general the events of one object get sorted in the correct order.

**Comment by arminkollascheck** [comment]
Cloud:
https://datashare.tu-dresden.de/s/3PXa8W538ixaQbf

**Comment by arminkollascheck** [comment]
Nice
