### ISSUE TITLE
Object list is not visible when importing an otevents-file

### ISSUE THREAD

**Issue by jobremer** [OpenTrafficCam/OTGroundTruther#66]
After importing an otevents-file, to make the objects visible in the list, you first have to go inti the drop down menu and choose any object class.

**Comment by arminkollascheck** [comment]
Thx for your bug report. Same as in #65 I couldnt reproduce this. Do you face the problem with the same videos/otevents as in #65?

**Comment by jobremer** [comment]
The problem occurs in any video/otevents that I import. This example is created with the same files as #65.
![emptylist](https://github.com/user-attachments/assets/9b0d2b98-8f1b-44e1-937d-de7db858db6a)

**Comment by arminkollascheck** [comment]
Hm, okay, for me it works, but I propably have different otevent files.

Can you upload the files (video+otevents) you use here please:
https://datashare.tu-dresden.de/s/jPq9B7KCmcoba7C

**Comment by jobremer** [comment]
Using the latest updates from the main branch solved both #65 & #66, thanks!

**Comment by arminkollascheck** [comment]
Nice.
